version: '3.8'

services:
  app:
    image: todolist:latest
    container_name: nestjs_app
    ports:
      - "4000:3000"
    env_file:
      - ../.env
    depends_on:
      mysql:
        condition: service_healthy # 確保 MySQL 完全啟動後才啟動 app
    restart: always

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    env_file:
      - ../.env
    ports:
      - "4306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
    driver: local
